-- MySQL Script generated by MySQL Workbench
-- Thu Nov 16 18:35:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sales_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sales_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sales_db` DEFAULT CHARACTER SET utf8 ;
USE `sales_db` ;

-- -----------------------------------------------------
-- Table `sales_db`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales_db`.`product` (
  `product_id` INT NOT NULL,
  `description` VARCHAR(90) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sales_db`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales_db`.`seller` (
  `seller_id` INT NOT NULL,
  `name` VARCHAR(90) NULL,
  `phone` BIGINT NULL,
  `birth_date` DATE NULL,
  `address` VARCHAR(180) NULL,
  PRIMARY KEY (`seller_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sales_db`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales_db`.`currency` (
  `currency_id` INT NOT NULL,
  `currency` VARCHAR(45) NULL DEFAULT 'USD',
  `to_dolar` DOUBLE NULL DEFAULT '0.75',
  PRIMARY KEY (`currency_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sales_db`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales_db`.`sale` (
  `transaction_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `sale_value` DOUBLE NOT NULL,
  `product_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  `currency_id` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `fk_sale_product_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_sale_seller1_idx` (`seller_id` ASC) VISIBLE,
  INDEX `fk_sale_currency1_idx` (`currency_id` ASC) VISIBLE,
  CONSTRAINT `fk_sale_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `sales_db`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_seller1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `sales_db`.`seller` (`seller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_currency1`
    FOREIGN KEY (`currency_id`)
    REFERENCES `sales_db`.`currency` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `sales_db`.`stage`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `sales_db`.`stage` (
  `transaction_id` INT NULL,
  `date` DATE NULL,
  `product_id` INT NULL,
  `seller_id` INT NULL,
  `sale_value` DOUBLE NULL,
  `currency` VARCHAR(45) NULL)
ENGINE = InnoDB


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
